# Generated by Django 5.M.6 on 2025-03-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                ("anime_id", models.IntegerField(primary_key=True, serialize=False)),
                ("anime_name", models.CharField(blank=True, max_length=255, null=True)),
                ("info_url", models.CharField(blank=True, max_length=255, null=True)),
                ("keyword", models.CharField(blank=True, max_length=255, null=True)),
                ("score", models.CharField(blank=True, max_length=255, null=True)),
                ("img_url", models.CharField(blank=True, max_length=255, null=True)),
                ("total", models.IntegerField(blank=True, null=True)),
                ("resume", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "anime",
                "managed": False,
            },
        ),
    ]
