# Generated by Django 5.M.6 on 2025-03-01 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Anime",
        ),
    ]
